"""add_feedback_to_alerts

Revision ID: 1ca59bbe2e79
Revises: a794e469f31e
Create Date: 2026-01-05 17:20:37.546213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca59bbe2e79'
down_revision: Union[str, Sequence[str], None] = 'a794e469f31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('feedback', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'feedback')
    # ### end Alembic commands ###
