"""add_mrn_to_patients

Revision ID: a794e469f31e
Revises: fa8a5d1f08f3
Create Date: 2026-01-05 13:02:20.978225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a794e469f31e'
down_revision: Union[str, Sequence[str], None] = 'fa8a5d1f08f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('mrn', sa.String(), nullable=True))
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_column('patients', 'mrn')
    # ### end Alembic commands ###
